server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}/${spring.application.version}
---

spring:
  application:
    name: user-manager
    version: v1
  profiles.active: postgres
  banner.location: banner.txt
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none # none create update
    show-sql: true
    properties.hibernate.format_sql: true
  sql.init.mode: never # always
  output.ansi.enabled: always
---

springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html